name: Build and Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

env:
  P4PORT: ${{ secrets.P4PORT }}
  P4USER: ${{ secrets.P4USER }}

jobs:
  build-and-deplot:
    runs-on: ubuntu-latest

    name: Build and Deploy

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout private action
        uses: actions/checkout@v2
        with:
          repository: perforce/setup-p4
          ref: master
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/setup-p4

      - name: p4 trust
        uses: ./.github/actions/setup-p4
        id: trust
        with:
          command: trust
          arguments: -y

      - name: p4 login
        uses: ./.github/actions/setup-p4
        id: login
        with:
          command: login          
        env:
          P4PASSWD: ${{ secrets.P4PASSWD }}  

      - name: Create Client Workspace
        uses: ./.github/actions/setup-p4
        with:
          command: client
          arguments: -i
          spec: |
            Client:	github-actions-p4
            Owner: ci
            Description:
              Created by ci
            Root:	$GITHUB_WORKSPACE
            Options:	noallwrite noclobber nocompress unlocked modtime rmdir
            SubmitOptions:	leaveunchanged
            LineEnd:	local
            View:
              //demo/... //github-actions-p4/base/...

      - name: p4 sync
        uses: ./.github/actions/setup-p4
        id: sync
        env:
          P4CLIENT: github-actions-p4
        with:
          command: sync
          arguments: -f

      - name: Build
        run: |
          echo "This is where your build steps would happen"



      - uses: EndBug/add-and-commit@v8 # You can change this to use a specific version.
        with:
          add: '.'
          # author_name: Andy Boutte
          # author_email: aboutte@perforce.com
          cwd: '.'

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actions

          # message: 'GitHub Actions Commit'

          # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
          # - ignore -> errors will be logged but the step won't fail
          # - exitImmediately -> the action will stop right away, and the step will fail
          # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
          # Default: ignore
          pathspec_error_handling: ignore

          # Arguments for the git pull command. By default, the action does not pull.
          # Default: ''
          # pull: '--rebase --autostash ...'

          push: true


      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4.2.3
      #   with:
      #     branch: gh-pages
      #     folder: base/

      - name: Create annotation that contains GitHub Pages URL
        run: |
          URL=$(gh api -X GET /repos/$GITHUB_REPOSITORY/pages | jq -r '.html_url')
          echo "::notice::Your GitHub Pages URL is: $URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
