name: Build and Deploy
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  get-p4-content:
    runs-on: ubuntu-latest
    name: Get P4 Content
    env:
      P4USER: ${{ secrets.P4USER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: p4 login
        uses: perforce/github-actions-p4
        id: login
        with:
          command: login
          global_options: "-p ${{ secrets.P4PORT }} -u ${{ secrets.P4USER }}"
        env:
          P4PASSWD: ${{ secrets.P4PASSWD }}

      - name: p4 depots
        uses: perforce/github-actions-p4
        id: depots
        with:
          command: depots

      - name: p4 client
        uses: perforce/github-actions-p4
        id: client
        with:
          command: client
          arguments: -i
          spec: |
            Client:	github-actions-p4

            Owner: ${{ secrets.P4USER }}

            Description:
              Created by ${{ secrets.P4USER }}.

            Root:	/tmp

            Options:	noallwrite noclobber nocompress unlocked modtime rmdir

            SubmitOptions:	leaveunchanged

            LineEnd:	local

            View:
              //Game/demactions/checkouto/... //github-actions-p4/Game/demo/...

      - name: p4 sync
        uses: perforce/github-actions-p4@v1
        id: sync
        env:
          P4CLIENT: github-actions-p4
        with:
          command: sync
          arguments: -f
      - name: Run build script
        run: ./.github/scripts/copy.sh
        shell: bash

  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.14.0]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn
          yarn run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
