name: Build and Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

env:
  P4PORT: ${{ secrets.P4PORT }}
  P4USER: ${{ secrets.P4USER }}

jobs:
  get-p4-content:
    runs-on: ubuntu-latest
    name: Build and Deploy
    env:
      P4USER: ${{ secrets.P4USER }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout private action
        uses: actions/checkout@v2
        with:
          repository: perforce/github-actions-p4
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/github-actions-p4

      - name: p4 trust
        uses: ./.github/actions/github-actions-p4
        id: trust
        with:
          command: trust
          arguments: -y

      - name: p4 login
        uses: ./.github/actions/github-actions-p4
        id: login
        with:
          command: login          
        env:
          P4PASSWD: ${{ secrets.P4PASSWD }}
          
      - name: p4 client
        uses: ./.github/actions/github-actions-p4
        id: client
        with:
          command: client
          arguments: -i
          spec: |
            Client:	github-actions-p4
            Owner: ci
            Description:
              Created by ci
            Root:	/github/home/
            Options:	noallwrite noclobber nocompress unlocked modtime rmdir
            SubmitOptions:	leaveunchanged
            LineEnd:	local
            View:
              //demo/assets/... //github-actions-p4/demo/assets/...

      - name: p4 sync
        uses: ./.github/actions/github-actions-p4
        id: sync
        env:
          P4CLIENT: github-actions-p4
        with:
          command: sync
          arguments: -f

      - name: Run build
        run: |
          mkdir -p $GITHUB_WORKSPACE/public/assets/models/ship_dark
          mkdir -p $GITHUB_WORKSPACE/public/assets/models/ship_light

          cp /home/runner/work/_temp/_github_home/demo/assets/ship/ship_dark.bin $GITHUB_WORKSPACE/public/assets/models/ship_dark/ship_dark.bin
          cp /home/runner/work/_temp/_github_home/demo/assets/ship/ship_dark.gltf $GITHUB_WORKSPACE/public/assets/models/ship_dark/scene.gltf

          # cp /home/runner/work/_temp/_github_home/demo/assets/ship/ship_light.bin $GITHUB_WORKSPACE/public/assets/models/ship_light/ship_light.bin
          # cp /home/runner/work/_temp/_github_home/demo/assets/ship/ship_light.gltf $GITHUB_WORKSPACE/public/assets/models/ship_light/scene.gltf

          cp /home/runner/work/_temp/_github_home/demo/assets/ship/ship_wreck.bin $GITHUB_WORKSPACE/public/assets/models/ship_light/ship_wreck.bin
          cp /home/runner/work/_temp/_github_home/demo/assets/ship/ship_wreck.gltf $GITHUB_WORKSPACE/public/assets/models/ship_light/scene.gltf

      - uses: actions/setup-node@v2
        with:
          node-version: 14.14.0
          
      - name: Install dependencies
        run: |
          yarn
          yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: dist
