name: Build and Deploy
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

env:
  P4PORT: ${{ secrets.P4PORT }}
  P4USER: ${{ secrets.P4USER }}

jobs:
  get-p4-content:
    runs-on: ubuntu-latest
    name: Get P4 Content
    env:
      P4USER: ${{ secrets.P4USER }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout private action
        uses: actions/checkout@v2
        with:
          repository: perforce/github-actions-p4
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: ./.github/actions/github-actions-p4

      - name: p4 trust
        uses: ./.github/actions/github-actions-p4
        id: trust
        with:
          command: trust
          arguments: -y

      - name: p4 login
        uses: ./.github/actions/github-actions-p4
        id: login
        with:
          command: login          
        env:
          P4PASSWD: ${{ secrets.P4PASSWD }}

      - name: Create p4 root
        run: |

          mkdir -p ~/.tmp/

      - name: p4 client
        uses: ./.github/actions/github-actions-p4
        id: client
        with:
          command: client
          arguments: -i
          spec: |
            Client:	github-actions-p4
            Owner: ci
            Description:
              Created by ci
            Root:	/home/runner/work/_temp
            Options:	noallwrite noclobber nocompress unlocked modtime rmdir
            SubmitOptions:	leaveunchanged
            LineEnd:	local
            View:
              //Game/assets/... //github-actions-p4/Game/assets/...

      - name: p4 sync
        uses: ./.github/actions/github-actions-p4
        id: sync
        env:
          P4CLIENT: github-actions-p4
        with:
          command: sync
          arguments: -f

      - name: Run build script
        run: |

          echo "this is the build step..."
          # RUNNER_TEMP=/home/runner/work/_temp
          # GITHUB_WORKSPACE=/home/runner/work/github-actions-demo-indie/github-actions-demo-indie
          pwd
          ls -la
          mkdir -p public/assets/ship/

          ls -la $RUNNER_TEMP/
          ls -la $RUNNER_TEMP/Game
          ls -la $RUNNER_TEMP/Game/assets/
          tree $RUNNER_TEMP
          #turn this into a symlink
          mv $RUNNER_TEMP/Game/assets/ship/* public/assets/ship/

      - uses: actions/setup-node@v2
        with:
          node-version: 14.14.0
      - name: Install dependencies
        run: |
          yarn
          yarn run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.




